project_id = "lbhtztbpxmqlzhyephew"

[functions.availability]
verify_jwt = false

[functions.book_reservation]
verify_jwt = false

[functions.agent_api]
verify_jwt = false

[functions.reminder_scheduler]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false
