// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.3";

// src/lib/mcp/tools/list-restaurants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser2(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-restaurants.ts
var list_restaurants_default = defineTool({
  name: "list_restaurants",
  title: "List restaurants",
  description: "List the restaurants the signed-in user has access to, with their id, name and slug.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("restaurants").select("id, name, slug, timezone, is_active").is("deleted_at", null);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { restaurants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-reservations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/identity.ts
var PROFILE_CEILING = {
  guest_voice: [
    "availability.read",
    "reservation.read",
    "reservation.create",
    "reservation.update",
    "reservation.cancel",
    "waitlist.create"
  ],
  guest_conversation: [
    "availability.read",
    "reservation.read",
    "reservation.create",
    "reservation.update",
    "reservation.cancel",
    "waitlist.create"
  ],
  workflow_agent: [
    "availability.read",
    "reservation.read",
    "reservation.create",
    "reservation.update",
    "reservation.cancel",
    "reservation.status.write",
    "waitlist.read",
    "waitlist.create",
    "guest.search",
    "reservation.note.write"
  ],
  operations_agent: [
    "availability.read",
    "reservation.read",
    "reservation.update",
    "reservation.status.write",
    "waitlist.read",
    "waitlist.create",
    "guest.search",
    "reservation.note.write",
    "deposit.read"
  ],
  manager_agent: [
    "availability.read",
    "reservation.read",
    "reservation.create",
    "reservation.update",
    "reservation.cancel",
    "reservation.status.write",
    "waitlist.read",
    "waitlist.create",
    "guest.search",
    "reservation.note.write",
    "large_group.approve",
    "large_group.decline",
    "table.override",
    "deposit.read"
  ],
  revenue_agent: ["availability.read", "reservation.read", "waitlist.read", "deposit.read"],
  system_automation: [
    "availability.read",
    "reservation.read",
    "reservation.status.write",
    "waitlist.read",
    "reservation.note.write"
  ]
};
var MANAGER_CAPABILITIES = [
  "availability.read",
  "reservation.read",
  "reservation.create",
  "reservation.update",
  "reservation.cancel",
  "reservation.status.write",
  "waitlist.read",
  "waitlist.create",
  "guest.search",
  "reservation.note.write",
  "large_group.approve",
  "large_group.decline",
  "table.override",
  "deposit.read"
];
var STAFF_CAPABILITIES = [
  "availability.read",
  "reservation.read",
  "reservation.create",
  "reservation.update",
  "reservation.cancel",
  "reservation.status.write",
  "waitlist.read",
  "waitlist.create",
  "guest.search",
  "reservation.note.write",
  "deposit.read"
];
var McpError = class extends Error {
  code;
  constructor(code, message) {
    super(message);
    this.code = code;
  }
};
async function resolveIdentity(ctx) {
  if (!ctx.isAuthenticated()) throw new McpError("unauthenticated", "Niet geauthenticeerd.");
  const token = ctx.getToken();
  if (!token) throw new McpError("unauthenticated", "Geen geldig token.");
  const userId = ctx.getUserId() ?? "";
  const sb = supabaseForUser2(ctx);
  const { data: svc } = await sb.from("mcp_service_identities").select("restaurant_id, profile, capabilities, revoked_at").eq("user_id", userId).is("revoked_at", null).maybeSingle();
  if (svc) {
    const profile = svc.profile;
    const ceiling = PROFILE_CEILING[profile] ?? [];
    const granted = (svc.capabilities ?? []).filter((c) => ceiling.includes(c));
    return {
      kind: "service",
      userId,
      profile,
      boundRestaurantId: svc.restaurant_id,
      capabilities: granted,
      sb,
      token
    };
  }
  return { kind: "human", userId, profile: null, boundRestaurantId: null, capabilities: [], sb, token };
}
async function humanCapabilities(identity, restaurantId) {
  const { data } = await identity.sb.from("restaurant_members").select("role").eq("restaurant_id", restaurantId).eq("user_id", identity.userId).maybeSingle();
  if (!data) return [];
  return ["owner", "manager"].includes(data.role) ? MANAGER_CAPABILITIES : STAFF_CAPABILITIES;
}
async function authorize(ctx, capability, explicitRestaurantId) {
  const identity = await resolveIdentity(ctx);
  let restaurantId;
  if (identity.kind === "service") {
    const bound = identity.boundRestaurantId;
    if (explicitRestaurantId && explicitRestaurantId !== bound) {
      throw new McpError("tenant_mismatch", "Deze koppeling heeft geen toegang tot dit restaurant.");
    }
    restaurantId = bound;
    if (!identity.capabilities.includes(capability)) {
      throw new McpError("capability_denied", `Deze koppeling mag '${capability}' niet uitvoeren.`);
    }
  } else {
    restaurantId = explicitRestaurantId ?? await onlyMembership(identity);
    const caps = await humanCapabilities(identity, restaurantId);
    if (caps.length === 0) {
      throw new McpError("tenant_mismatch", "Geen toegang tot dit restaurant.");
    }
    if (!caps.includes(capability)) {
      throw new McpError("capability_denied", `Je rol mag '${capability}' niet uitvoeren.`);
    }
    identity.capabilities = caps;
  }
  return { identity, restaurantId, sb: identity.sb };
}
async function onlyMembership(identity) {
  const { data, error } = await identity.sb.from("restaurant_members").select("restaurant_id").eq("user_id", identity.userId).limit(5);
  if (error) throw new McpError("internal", error.message);
  const ids = Array.from(new Set((data ?? []).map((r) => r.restaurant_id)));
  if (ids.length === 0) throw new McpError("tenant_mismatch", "Geen restaurant gevonden voor dit account.");
  if (ids.length > 1) {
    throw new McpError("restaurant_required", "Meerdere restaurants \u2014 geef restaurant_id mee (zie list_restaurants).");
  }
  return ids[0];
}

// src/lib/mcp/tools/list-reservations.ts
var list_reservations_default = defineTool2({
  name: "list_reservations",
  title: "List reservations",
  description: "List reservations for a date (or date range) for a restaurant, ordered by start time. Cancelled reservations are excluded unless include_cancelled is true.",
  inputSchema: {
    date: z.string().describe("Date in YYYY-MM-DD. Defaults to today."),
    end_date: z.string().optional().describe("Optional end date (YYYY-MM-DD) for a range."),
    restaurant_id: z.string().optional().describe("Restaurant id; optional when the user has one restaurant."),
    include_cancelled: z.boolean().optional(),
    limit: z.number().optional().describe("Max rows to return, default 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, end_date, restaurant_id, include_cancelled, limit }, ctx) => {
    try {
      const { restaurantId: rid, sb } = await authorize(ctx, "reservation.read", restaurant_id);
      const from = date || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      const to = end_date || from;
      const cap = Math.min(Math.max(limit ?? 100, 1), 200);
      let q = sb.from("reservations").select(
        "id, reservation_date, start_time, end_time, party_size, status, channel, guest_first_name, guest_last_name, guest_phone, guest_email, special_requests, dietary_notes, large_group_status, requires_manual_approval"
      ).eq("restaurant_id", rid).gte("reservation_date", from).lte("reservation_date", to).order("start_time", { ascending: true }).limit(cap);
      if (!include_cancelled) q = q.neq("status", "cancelled");
      const { data, error } = await q;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? []) }],
        structuredContent: { restaurant_id: rid, reservations: data ?? [] }
      };
    } catch (e) {
      return { content: [{ type: "text", text: e instanceof Error ? e.message : String(e) }], isError: true };
    }
  }
});

// src/lib/mcp/tools/get-reservation.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_reservation_default = defineTool3({
  name: "get_reservation",
  title: "Get reservation",
  description: "Get the full details of one reservation by its id.",
  inputSchema: { reservation_id: z2.string().describe("Reservation id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ reservation_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("reservations").select(
      "id, restaurant_id, reservation_date, start_time, end_time, party_size, status, channel, source_label, confirmation_code, guest_id, guest_first_name, guest_last_name, guest_email, guest_phone, guest_language, special_requests, dietary_notes, internal_notes, occasion, prefers_terrace, requires_manual_approval, large_group_status, deposit_required, deposit_status, no_show_risk, created_at, updated_at"
    ).eq("id", reservation_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Reservering niet gevonden." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reservation: data }
    };
  }
});

// src/lib/mcp/tools/search-guests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z3 } from "npm:zod@^3.25.76";
var search_guests_default = defineTool4({
  name: "search_guests",
  title: "Search guests",
  description: "Search the guest book by name, email or phone. Returns visit history, VIP flag and allergies.",
  inputSchema: {
    query: z3.string().describe("Name, email or phone fragment to search for."),
    restaurant_id: z3.string().optional().describe("Restaurant id; optional when the user has one restaurant."),
    limit: z3.number().optional().describe("Max rows, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, restaurant_id, limit }, ctx) => {
    try {
      const { restaurantId: rid, sb } = await authorize(ctx, "guest.search", restaurant_id);
      const cap = Math.min(Math.max(limit ?? 20, 1), 50);
      const term = query.trim().replace(/[%,]/g, " ");
      const { data, error } = await sb.from("guests").select(
        "id, first_name, last_name, full_name, email, phone, is_vip, is_blacklisted, allergies, dietary_preferences, seating_preferences, hospitality_notes, total_visits, no_show_count, last_visit_at, tags"
      ).eq("restaurant_id", rid).is("deleted_at", null).or(
        `full_name.ilike.%${term}%,first_name.ilike.%${term}%,last_name.ilike.%${term}%,email.ilike.%${term}%,phone.ilike.%${term}%`
      ).order("last_visit_at", { ascending: false, nullsFirst: false }).limit(cap);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? []) }],
        structuredContent: { restaurant_id: rid, guests: data ?? [] }
      };
    } catch (e) {
      return { content: [{ type: "text", text: e instanceof Error ? e.message : String(e) }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-waitlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_waitlist_default = defineTool5({
  name: "list_waitlist",
  title: "List waitlist",
  description: "List waitlist entries for a date, with party size, desired time window and status.",
  inputSchema: {
    date: z4.string().describe("Desired date in YYYY-MM-DD. Defaults to today."),
    restaurant_id: z4.string().optional().describe("Restaurant id; optional when the user has one restaurant."),
    status: z4.string().optional().describe("Optional status filter, e.g. waiting, notified, converted.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, restaurant_id, status }, ctx) => {
    try {
      const { restaurantId: rid, sb } = await authorize(ctx, "waitlist.read", restaurant_id);
      const day = date || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      let q = sb.from("waitlist_entries").select(
        "id, desired_date, desired_time_from, desired_time_to, party_size, first_name, last_name, phone, email, status, notes, notified_at, matched_at, created_at"
      ).eq("restaurant_id", rid).eq("desired_date", day).order("created_at", { ascending: true }).limit(100);
      if (status) q = q.eq("status", status);
      const { data, error } = await q;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data ?? []) }],
        structuredContent: { restaurant_id: rid, entries: data ?? [] }
      };
    } catch (e) {
      return { content: [{ type: "text", text: e instanceof Error ? e.message : String(e) }], isError: true };
    }
  }
});

// src/lib/mcp/tools/add-reservation-note.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z5 } from "npm:zod@^3.25.76";
var add_reservation_note_default = defineTool6({
  name: "add_reservation_note",
  title: "Add internal note to reservation",
  description: "Append an internal note to a reservation. Internal notes are only visible to staff, never to the guest.",
  inputSchema: {
    reservation_id: z5.string().describe("Reservation id (uuid)."),
    note: z5.string().describe("The note to append.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ reservation_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const text = note.trim();
    if (!text) return { content: [{ type: "text", text: "Notitie mag niet leeg zijn." }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data: current, error: readErr } = await sb.from("reservations").select("id, internal_notes").eq("id", reservation_id).maybeSingle();
    if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
    if (!current) return { content: [{ type: "text", text: "Reservering niet gevonden." }], isError: true };
    const stamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 16).replace("T", " ");
    const merged = [current.internal_notes?.trim(), `[${stamp}] ${text}`].filter(Boolean).join("\n");
    const { data, error } = await sb.from("reservations").update({ internal_notes: merged }).eq("id", reservation_id).select("id, internal_notes").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reservation: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lbhtztbpxmqlzhyephew";
var mcp_default = defineMcp({
  name: "tx-tablewise",
  title: "TX TableWise",
  version: "0.1.0",
  instructions: "Tools for TX TableWise, a reservation and floor management system for restaurants. Use list_restaurants first when the user manages more than one venue. list_reservations and get_reservation read the booking agenda, search_guests reads the guest book, list_waitlist reads the waitlist, and add_reservation_note appends a staff-only note. All data is scoped to the signed-in user's restaurants.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_restaurants_default, list_reservations_default, get_reservation_default, search_guests_default, list_waitlist_default, add_reservation_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
